name: dev-journal
services:
- name: web
  environment_slug: python
  instance_size_slug: basic-xxs
  instance_count: 1
  run_command: python manage.py migrate && gunicorn journal.wsgi:application
  routes:
    - path: /
  envs:
    - key: DJANGO_SETTINGS_MODULE
      value: journal.settings
    - key: SECRET_KEY
      scope: RUN_AND_BUILD_TIME
    - key: DEBUG
      scope: RUN_AND_BUILD_TIME
    - key: ALLOWED_HOSTS
      scope: RUN_AND_BUILD_TIME
    - key: DB_NAME
      scope: RUN_AND_BUILD_TIME
    - key: DB_USER
      scope: RUN_AND_BUILD_TIME
    - key: DB_PASSWORD
      scope: RUN_AND_BUILD_TIME
    - key: DB_HOST
      scope: RUN_AND_BUILD_TIME
    - key: DB_PORT
      scope: RUN_AND_BUILD_TIME
  github:
    repo: markdmyers01/dev-journal
    branch: main
    deploy_on_push: true
